# Generated by Django 5.2.9 on 2025-12-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import modules.base.media.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=modules.base.media.models.media_upload_path)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "🖼️ Image"),
                            ("video", "🎬 Video"),
                            ("audio", "🎵 Audio"),
                            ("document", "📄 Document"),
                            ("other", "📎 Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0, help_text="Size in bytes")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["file_type", "-created_at"], name="media_files_file_ty_f91ab8_idx"),
                    models.Index(fields=["uploaded_by", "-created_at"], name="media_files_uploade_b2f6b5_idx"),
                ],
            },
        ),
    ]
