# Generated by Django 5.2.9 on 2025-12-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daemon_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, help_text="Short bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, help_text="Profile picture", null=True, upload_to="profiles/"),
        ),
    ]
