# Generated by Django 5.2.9 on 2025-12-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='vision/uploads/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('source_url', models.URLField(blank=True, help_text='Original YouTube/Web URL', max_length=500)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, default=0.0, help_text='Video duration', null=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('analysis_provider', models.CharField(blank=True, help_text='e.g., MediaPipe, YOLO', max_length=50)),
            ],
            options={
                'db_table': 'vision_visual_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.CharField(choices=[('POSE', 'Pose Estimation'), ('HAND', 'Hand Tracking'), ('OBJECT', 'Object Detection (YOLO)'), ('FACE', 'Face Mesh')], max_length=50)),
                ('raw_data', models.JSONField(help_text='Standardized JSON: {frames: [{timestamp: 0, keypoints: [...]}]}')),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='vision.visualmedia')),
            ],
            options={
                'db_table': 'vision_analysis_result',
            },
        ),
    ]
