# Generated by Django 5.2.9 on 2025-12-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(default="DAEMON-ONE", help_text="Site display name", max_length=100)),
                (
                    "site_description",
                    models.TextField(
                        blank=True, default="AI-First Django Template", help_text="Short site description"
                    ),
                ),
                ("logo", models.ImageField(blank=True, help_text="Site logo image", null=True, upload_to="settings/")),
                (
                    "favicon",
                    models.ImageField(blank=True, help_text="Favicon image (32x32)", null=True, upload_to="settings/"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, default="DAEMON-ONE", help_text="Default meta title for pages", max_length=60
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        default="AI-First Django Template with Hypermedia-Driven Architecture",
                        help_text="Default meta description",
                        max_length=160,
                    ),
                ),
                ("meta_keywords", models.CharField(blank=True, help_text="Comma-separated keywords", max_length=255)),
                ("contact_email", models.EmailField(blank=True, help_text="Public contact email", max_length=254)),
                ("support_email", models.EmailField(blank=True, help_text="Support email address", max_length=254)),
                ("twitter_handle", models.CharField(blank=True, max_length=50)),
                ("github_url", models.URLField(blank=True)),
                ("discord_url", models.URLField(blank=True)),
                ("maintenance_mode", models.BooleanField(default=False, help_text="Enable maintenance mode")),
                ("allow_registration", models.BooleanField(default=True, help_text="Allow new user registration")),
                ("enable_ai_features", models.BooleanField(default=True, help_text="Enable AI-powered features")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
