# Generated by Django 5.2.9 on 2025-12-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, help_text="Model or resource type (e.g., 'User', 'Order')", max_length=100
                    ),
                ),
                ("resource_id", models.CharField(blank=True, help_text="ID of the affected resource", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="audit_audit_user_id_429f6b_idx"),
                    models.Index(fields=["action", "-created_at"], name="audit_audit_action_0c6a84_idx"),
                    models.Index(fields=["resource_type", "resource_id"], name="audit_audit_resourc_2a3aef_idx"),
                ],
            },
        ),
    ]
