# Generated by Django 5.2.9 on 2025-12-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_pdf', models.FileField(upload_to='research/papers/%Y/%m/%d/')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('extracted_markdown', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'research_smart_paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('target_text', models.TextField(blank=True)),
                ('position_selector', models.JSONField(default=dict, help_text='PDF coordination or DOM selector')),
                ('content', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='smart_paper.researchpaper')),
            ],
            options={
                'db_table': 'research_paper_annotation',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latex_original', models.TextField()),
                ('python_expression', models.TextField(blank=True, help_text='Executable Python code for this formula')),
                ('variables_metadata', models.JSONField(default=dict, help_text='Schema for variables: name, unit, default_value')),
                ('description', models.TextField(blank=True)),
                ('location_index', models.IntegerField(default=0, help_text='Position ordering in the document')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='smart_paper.researchpaper')),
            ],
            options={
                'db_table': 'research_formula_snippet',
                'ordering': ['location_index'],
            },
        ),
    ]
